name = "drupal"
type = "javascript"
workers_dev = false
compatibility_date = "2022-01-16"

[build]
command = "rollup --config"

[build.upload]
format = "modules"
main = "./worker.mjs"

[durable_objects]
bindings = [
  { name = "CACHE_TAG", class_name = "CacheTag" }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["CacheTag"] # Array of new classes
