name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Test, Build, Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: terraform fmt -check -diff
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
      - if: github.ref != 'refs/heads/master'
        run: terraform plan
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      - if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
