name: Build
on:
  push:
  pull_request:
  repository_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm install
      - run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: 'test'
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        site: ['davidwbarratt', 'sailvenice']
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: ${{ matrix.site }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
