name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Test, Build, Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npm test
      - run: npm run build
      - if: github.ref == 'refs/heads/master'
        run: npm run publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
